name: Python package

on: [push]
env:
  POETRY_VERSION: 1.0

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PYTHON_VERSION: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{matrix.PYTHON_VERSION}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.PYTHON_VERSION}}
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==${{env.POETRY_VERSION}}
    - name: Install deps
      run: |
        poetry install
    - name: Run pytest
      run: |
        poetry run python -m pytest --cov=pyfgaws --cov-report=xml --cov-branch 
    - name: Style checking
      run: |
        poetry run black --line-length 99 --check pyfgaws
    - name: Run lint
      run: |
        poetry run flake8 --config=ci/flake8.cfg pyfgaws
    - name: Run mypy
      run: |
        poetry run mypy -p pyfgaws --config=ci/mypy.ini
    - name: Upload code coverage
      uses: codecov/codecov-action@v1.0.7
