name: Python package

on: [push]
env:
  POETRY_VERSION: 1.8.3

jobs:
  testing:
    runs-on: ubuntu-24.04
    environment: github-actions-ci
    strategy:
      matrix:
        PYTHON_VERSION: ["3.10", "3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

    - name: Set up Python ${{matrix.PYTHON_VERSION}}
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
      with:
        python-version: ${{matrix.PYTHON_VERSION}}

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo "version=$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info))")" >> "$GITHUB_OUTPUT"

    - name: Install poetry
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install poetry==${{env.POETRY_VERSION}}

    - name: Configure poetry
      shell: bash
      run: poetry config virtualenvs.in-project true

    - name: Set up cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv

    - name: Install deps
      shell: bash
      run: |
        poetry install

    - name: Run pytest
      shell: bash
      run: |
        poetry run python -m pytest --cov=pyfgaws --cov-report=xml --cov-branch

    - name: Style checking
      shell: bash
      run: |
        poetry run black --line-length 99 --check pyfgaws

    - name: Run lint
      shell: bash
      run: |
        poetry run flake8 --config=ci/flake8.cfg pyfgaws

    - name: Run mypy
      shell: bash
      run: |
        poetry run mypy -p pyfgaws --config=ci/mypy.ini

    - name: Upload code coverage
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5.5.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
